### ISSUE TITLE
Authentication Manager not initializing when you application properties

### ISSUE THREAD

**Issue by picaso** [ulisesbocchio/spring-boot-security-saml#25]
When I use just application properties with my spring-boot service provider, the application refuses to start and throws this error:

`Caused by: org.springframework.beans.FatalBeanException: A dependency cycle was detected when trying to resolve the AuthenticationManager. Please ensure you have configured authentication.
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.validateBeanCycle(WebSecurityConfigurerAdapter.java:475) ~[spring-security-config-4.0.4.RELEASE.jar:4.0.4.RELEASE]
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.<init>(WebSecurityConfigurerAdapter.java:437) ~[spring-security-config-4.0.4.RELEASE.jar:4.0.4.RELEASE]
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.authenticationManagerBean(WebSecurityConfigurerAdapter.java:220) ~[spring-security-config-4.0.4.RELEASE.jar:4.0.4.RELEASE]
	at com.github.ulisesbocchio.spring.boot.security.saml.configuration.SAMLServiceProviderSecurityConfiguration$SAMLWebSecurityConfigurer.authenticationManagerBean(SAMLServiceProviderSecurityConfiguration.java:174) ~[spring-boot-security-saml-1.10.jar:na]
	at com.github.ulisesbocchio.spring.boot.security.saml.configuration.SAMLServiceProviderSecurityConfiguration$SAMLWebSecurityConfigurer$$EnhancerBySpringCGLIB$$932095ec.CGLIB$authenticationManagerBean$1(<generated>) ~[spring-boot-security-saml-1.10`

if I try to create as bean instance of AuthenticationManager via  extending WebSecurityConfigurerAdapter, I get a 
`aused by: org.springframework.security.config.annotation.AlreadyBuiltException: This object has already been built` error.

Caveat: I am using gradle instead of maven. I am not entirely sure whats going on here.

**Comment by ulisesbocchio** [comment]
Can you share your app code and configuration?

**Comment by jzimermann** [comment]
@picaso @ulisesbocchio it seems the issue is related to the Spring Boot version. The make it work, you'll need to migrate your Spring Boot to version 1.4.0.RELEASE or +.

**Comment by ulisesbocchio** [comment]
thanks @jzimermann, what version of Spring Boot are you using @picaso ?

**Comment by ulisesbocchio** [comment]
Did you check out [this](https://github.com/ulisesbocchio/spring-boot-security-saml-samples/tree/master/spring-boot-security-saml-demo-props) sample @picaso ? It works with only properties. Can you share which properties are you trying to configure your SP with?

**Comment by picaso** [comment]
Thanks. We were using spring 1.3.5. Upgrading to 1.4 solves the problem. Thanks.
