### ISSUE TITLE
NPE when extending WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by nixgadget** [ulisesbocchio/spring-boot-security-saml#37]
I get the following NPE when extend `WebSecurityConfigurerAdapter`

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at com.orchestral.dsm.onboarding.OnboardingApp.main(OnboardingApp.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 23 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.github.ulisesbocchio.spring.boot.security.saml.configurer.ServiceProviderBuilder.beforeInit(ServiceProviderBuilder.java:87)
	at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:324)
	at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41)
	at com.github.ulisesbocchio.spring.boot.security.saml.bean.SAMLConfigurerBean.init(SAMLConfigurerBean.java:225)
	at com.github.ulisesbocchio.spring.boot.security.saml.bean.SAMLConfigurerBean.init(SAMLConfigurerBean.java:137)
	at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.init(AbstractConfiguredSecurityBuilder.java:371)
	at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:325)
	at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41)
	at org.springframework.security.config.annotation.web.builders.WebSecurity.performBuild(WebSecurity.java:290)
	at org.springframework.security.config.annotation.web.builders.WebSecurity.performBuild(WebSecurity.java:77)
	at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:334)
	at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41)
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:104)
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$76b74b3e.CGLIB$springSecurityFilterChain$1(<generated>)
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$76b74b3e$$FastClassBySpringCGLIB$$f2f3ff1f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$76b74b3e.springSecurityFilterChain(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 24 common frames omitted
```

My code is as follows,

```
@Configuration("ssoSecurityConfiguration")
@Order(1)
public class SSOSecurityConfiguration extends WebSecurityConfigurerAdapter {
    @Bean
    public SAMLConfigurerBean saml() {
        return new SAMLConfigurerBean();
    }

    @Bean
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }

    @Override
    public void configure(HttpSecurity http) throws Exception {

        http
            .httpBasic()
                .disable()
                .csrf()
                .disable()
                .anonymous()
            .and()
                .apply(saml())
                .serviceProvider()
                .metadataGenerator() //(1)
                .entityId("test")
                .entityBaseURL("http://localhost:8080")
            .and()
                .sso() //(2)
                .defaultSuccessURL("/home")
                .idpSelectionPageURL("/idpselection")
            .and()
                .logout() //(3)
                .defaultTargetURL("/")
            .and()
                .metadataManager() //(4)
                .metadataLocations("classpath:/sso/idp-test.xml")
                .refreshCheckInterval(0)
            .and()
                .extendedMetadata() //(5)
                .idpDiscoveryEnabled(true)
            .and()
                .keyManager() //(6)
                .privateKeyDERLocation("classpath:/sso/localhost.key.der")
                .publicKeyPEMLocation("classpath:/sso/localhost.pem")
            .and()
                .http()
                    .authorizeRequests()
                    .anyRequest()
                    .permitAll()
                .and()
                    .authorizeRequests()
                    .anyRequest()
                    .authenticated();
    }
}
```

I also have `@EnableSAMLSSO` in the main class

The NPE seems to be pointing to this line in the `ServiceProviderBuilder` class,

```
    @Override
    protected void beforeInit() throws Exception {
        //All configurers are initialized only once.
        //Order of configurers is established by the following stream.
        boolean lbEnabled = getSharedObject(SAMLSSOProperties.class).getContextProvider().getLb().isEnabled();
    }
```

What am i possibly doing wrong here ? Following the example.

**Comment by ruoat** [comment]
I encountered the same issue yesterday. Everything worked fine before. I did some refactorings and now Mac and Windows can build jar, which works, but Linux builds jar, which throws that error. I have been using spring-boot-security-saml 1.10 and the error is slightly different but crashes to getSharedObject(SAMLSSOProperties.class) being null.

Now I updated to 1.12 and get the same error in Linux build. I compared jars produced by Linux and Mac and differences were in the order of classes. I guess this is some classloader issue.

**Comment by ruoat** [comment]
I managed to prevent this issue by removing `@EnableWebSecurity`. I have many `WebSecurityConfigurerAdapter`s but found that that annotation is not needed anymore in our setup. In Windows or Mac builds that annotation would not cause any problems but Linux build ordered classes that the nullpointerexception occurred. @nixgadget maybe you should check that there is not `@EnableWebSecurity` specified?

**Comment by ulisesbocchio** [comment]
EnableWebSecurity is adding some default configs for security but if you define your own WebSecurityConfigurerAdapter you may not need it. I have found similar issues with EnableWebSecurity and the way configurers are ordered and analyzed.

**Comment by ulisesbocchio** [comment]
I'm closing this since I haven't seen any further traction, but just to clarify, the line throwing the NPE:
```java
boolean lbEnabled = getSharedObject(SAMLSSOProperties.class).getContextProvider().getLb().isEnabled();
```
is purely reading configuration.
`SAMLSSOProperties` is just a `ConfigProperties` bean that initializes:
```java
    @NestedConfigurationProperty
    private SAMLContextProviderProperties contextProvider = new SAMLContextProviderProperties();
```
And `SAMLContextProviderProperties` initializes:
```java
    @NestedConfigurationProperty
    private SAMLContextProviderLBProperties lb = new SAMLContextProviderLBProperties();
```
and `SAMLContextProviderLBProperties` initializes:
```java
boolean enabled = false;
```
So I don't see how that line would throw a NPE unless something is messing with the beans...
